
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://beefjsdgrdeiymzxwxru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlZWZqc2RncmRlaXltenh3eHJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MzI1OTQsImV4cCI6MjA1ODUwODU5NH0.knvlRdFYtN2bl3t3I4O8v3dU_MWKDDuaBZkvukdU87w";
const SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlZWZqc2RncmRlaXltenh3eHJ1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MjkzMjU5NCwiZXhwIjoyMDU4NTA4NTk0fQ.7alp-dJOJPuUEjiWb71LOFlRFE6QrQQxuXXSTBJwyAM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: typeof window !== 'undefined' ? window.localStorage : undefined,
    detectSessionInUrl: true
  }
});

/**
 * Enhanced function to ensure we always have a valid session
 * with special handling for owner role users
 */
export const getAuthenticatedClient = async () => {
  try {
    // Check if user data exists in localStorage (for owner role)
    const isOwnerFallbackEnabled = await checkForOwnerFallback();
    if (isOwnerFallbackEnabled) {
      console.log("Owner role detected, using service role client for operation");
      // For owner users, use the service role client to avoid authentication issues
      return supabaseAdmin;
    }
    
    // Regular session handling
    const { data: { session }, error: sessionError } = await supabase.auth.getSession();
    
    if (sessionError) {
      console.error("Session error:", sessionError);
      throw new Error("Error al verificar la sesión: " + sessionError.message);
    }
    
    // If no session or it's about to expire, try refreshing
    if (!session || (session.expires_at && session.expires_at < Math.floor(Date.now() / 1000) - 60)) {
      console.log("Session not found or expiring soon, attempting refresh...");
      
      // Try refreshing the session
      const { data, error: refreshError } = await supabase.auth.refreshSession();
      
      if (refreshError) {
        console.error("Session refresh error:", refreshError);
        
        // Check again for owner fallback after refresh failure
        if (await checkForOwnerFallback()) {
          console.log("Owner fallback activated after failed refresh");
          return supabaseAdmin;
        }
        
        throw new Error("La sesión expiró y no se pudo refrescar. Por favor inicie sesión nuevamente.");
      }
      
      if (!data.session) {
        console.warn("Session refresh did not return a valid session");
        
        // Check for owner fallback after no session returned
        if (await checkForOwnerFallback()) {
          console.log("Owner fallback activated after no session from refresh");
          return supabaseAdmin;
        }
        
        throw new Error("No se pudo restaurar la sesión. Por favor inicie sesión nuevamente.");
      }
      
      console.log("Session refreshed successfully");
      return supabase;
    }
    
    console.log("Using existing valid session");
    return supabase;
  } catch (error) {
    console.error("Error in getAuthenticatedClient:", error);
    
    // Final check for owner fallback
    if (await checkForOwnerFallback()) {
      console.log("Owner fallback activated in error handler");
      return supabaseAdmin;
    }
    
    throw error;
  }
};

/**
 * Helper function to check if the current user has owner role
 * and should be allowed to bypass normal authentication
 */
const checkForOwnerFallback = async (): Promise<boolean> => {
  try {
    // Check user data in localStorage
    const currentUserStr = localStorage.getItem('current_user');
    if (!currentUserStr) return false;
    
    try {
      const userData = JSON.parse(currentUserStr);
      if (userData && userData.role === 'owner') {
        console.log("Owner role detected in local storage");
        return true;
      }
    } catch (e) {
      console.error("Error parsing user data:", e);
    }
    
    return false;
  } catch (e) {
    console.error("Error checking for owner fallback:", e);
    return false;
  }
};

// Cliente con service role para operaciones administrativas
export const supabaseAdmin = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_SERVICE_ROLE_KEY,
  {
    auth: {
      autoRefreshToken: false,
      persistSession: false
    }
  }
);
